### ISSUE TITLE
Review number of Gunicorn workers and threads 

### ISSUE THREAD

**Issue by jw35** [SmartCambridge/tfc_web#267]
gunicorn --workers 3 --threads 3 --worker-class gthread

probably only allows 9 simultaneous requests. This may not be enough.

**Comment by abrahammartin** [comment]
done in https://github.com/SmartCambridge/tfc_web/commit/9904772226f53dfb8b9343cb8fe9864ddf1866cf but I'll wait to close this until we know it has improved performance

**Comment by jw35** [comment]
Subsequently change this again in 0916119 as part of PR #271. Initial indications are promising...

**Comment by jw35** [comment]
Still looks good, with smartcambridge.org generally running at ~50% memory in use. Closing this.
