### ISSUE TITLE
Internal Server Error: /transport/stop/

### ISSUE THREAD

**Issue by jw35** [SmartCambridge/tfc_web#321]
Calling /transport/stop/ without a stop-id causes and Internal Server Error exception (details below). This seems to be because the URL patterns explicitly allow this usage:

https://github.com/SmartCambridge/tfc_web/blob/218b4a3271e1ee7d29aef1d1ae7f5d823fb511c1/tfc_web/transport/urls.py#L28-L29

but the view code considers the bus_stop_id parameter to be compulsory:

https://github.com/SmartCambridge/tfc_web/blob/218b4a3271e1ee7d29aef1d1ae7f5d823fb511c1/tfc_web/transport/views.py#L44

I assume the fix would be to remove the presumably redundant URL pattern.

```
Internal Server Error: /transport/stop/

TypeError at /transport/stop/
bus_stop() missing 1 required positional argument: 'bus_stop_id'

Traceback:  

File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
 41.             response = get_response(request)

File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
 249.             response = self._get_response(request)

File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
 187.                 response = self.process_exception_by_middleware(e, request)

File "/home/tfc_prod/tfc_web_venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
 185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

Exception Type: TypeError at /transport/stop/
Exception Value: bus_stop() missing 1 required positional argument: 'bus_stop_id'
```

**Comment by abrahammartin** [comment]
Yup, old code no longer in use since we moved to use the new stop view. Fixed in https://github.com/SmartCambridge/tfc_web/commit/0d6fcef5f9e12d9982f390aebb3f75aa87595ce3
