### ISSUE TITLE
Service worker loaded with relative URL in templates/base.html

### ISSUE THREAD

**Issue by jw35** [SmartCambridge/tfc_web#337]
templates/base.html (used by many/most pages) loads sw.js with a relative URL

https://github.com/SmartCambridge/tfc_web/blob/1f4d77eda395422fc17608e7b675ce226ac29295/tfc_web/templates/base.html#L17

which causes 404 not found for any page not at the root of the site. Presumably this should be 
`"/sw.js"` as in pocket.html:

https://github.com/SmartCambridge/tfc_web/blob/1f4d77eda395422fc17608e7b675ce226ac29295/tfc_web/smartpanel/templates/smartpanel/pocket.html#L18

**Comment by jw35** [comment]
@abrahammartin Is this the simple fix I think it is? It's causing annoying (though not service affecting) Internal Server Errors...

**Comment by abrahammartin** [comment]
You are absolutely right. Sorry I missed the initial bug report. PR submitted now.
